"""mig 5

Revision ID: 11f2cfb74654
Revises: 
Create Date: 2024-04-08 23:46:00.357018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11f2cfb74654'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id', nullable=False, new_column_name="id")
    op.add_column('messages', sa.Column('id', sa.Uuid(), nullable=False))
    op.alter_column('messages', 'text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint('messages_receiver_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.drop_column('messages', 'message_id')
    op.drop_column('messages', 'joined_at')
    op.add_column('users', sa.Column('joined_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('avatar', sa.BigInteger(), nullable=False))
    op.alter_column('users', 'tg_user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'tg_user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'joined_at')
    op.drop_column('users', 'id')
    op.add_column('messages', sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['user_id'])
    op.create_foreign_key('messages_receiver_id_fkey', 'messages', 'users', ['receiver_id'], ['user_id'])
    op.alter_column('messages', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('messages', 'id')
    # ### end Alembic commands ###
