"""mig 5

Revision ID: 56311a8e8249
Revises: 11f2cfb74654
Create Date: 2024-04-08 23:53:08.201658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56311a8e8249'
down_revision: Union[str, None] = '11f2cfb74654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
